apiVersion: v1
appVersion: "1.5.0"
description: This Chart seemlessly integrates Kubernetes with AWS ECR
name: aws-ecr-credential
version: 1.5.0
keywords:
- aws ecr
- imagePullSecrets
- kubernetes
sources:
  - https://github.com/woodjme/aws-ecr-credential/aws-ecr-credential
